#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidToAppleVectorLogo.Resource", IsApplication=true)]

namespace AndroidToAppleVectorLogo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f050000
			public const int body_shrink = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int body_shrink_reverse = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int green_to_black = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int green_to_black_reverse = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int head_leaf_transition = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int head_leaf_transition_reverse = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int left_antenna_shrink = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int left_antenna_shrink_reverse = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int left_arm_apple_transition = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int left_arm_apple_transition_reverse = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int left_eye_close = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int left_eye_close_reverse = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int reset_body = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int reset_head = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int reset_left_arm = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int reset_right_arm = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int reset_to_black = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int reset_to_gone_state = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int reset_to_green = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int right_antenna_shrink = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int right_antenna_shrink_reverse = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int right_arm_apple_transition = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int right_arm_apple_transition_reverse = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int right_eye_close = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int right_eye_close_reverse = 2131034136;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int android_green = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int apple_black = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int eye_white = 2131099650;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int activity_horizontal_margin = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int activity_vertical_margin = 2131165185;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android_logo_vector_morphable = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apple_logo_vector_morphable = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int consolidated_animated_vector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int consolidated_animated_vector_reverse = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0001
			public const int action_settings = 2131492865;
			
			// aapt resource value: 0x7f0c0000
			public const int path_morph_animated_vector = 2131492864;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int blinking_time = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int morphing_time = 2131361793;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int menu_main = 2131427328;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080002
			public const int action_settings = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int android_head = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7f080012
			public const int apple_leaf = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int apple_left_half = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int apple_right_half = 2131230740;
			
			// aapt resource value: 0x7f080010
			public const int body = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int body_shrunk = 2131230737;
			
			// aapt resource value: 0x7f080001
			public const int hello_world = 2131230721;
			
			// aapt resource value: 0x7f080009
			public const int left_antenna_gone = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int left_antenna_normal = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int left_arm = 2131230732;
			
			// aapt resource value: 0x7f080005
			public const int left_eye_closed = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int left_eye_open = 2131230724;
			
			// aapt resource value: 0x7f08000e
			public const int left_leg = 2131230734;
			
			// aapt resource value: 0x7f08000b
			public const int right_antenna_gone = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int right_antenna_normal = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int right_arm = 2131230733;
			
			// aapt resource value: 0x7f080007
			public const int right_eye_closed = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int right_eye_open = 2131230726;
			
			// aapt resource value: 0x7f08000f
			public const int right_leg = 2131230735;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
