#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EndlessPinJump.Resource", IsApplication=true)]

namespace EndlessPinJump
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int dot = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int pin = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int avd_endless_pin_jump = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int avd_endless_pin_jump_1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int avd_endless_pin_jump_2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int avd_endless_pin_jump_3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int avd_endless_pin_jump_4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int avd_endless_pin_jump_5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int avd_endless_pin_jump_6 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int avd_endless_pin_jump_7 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int avd_endless_pin_jump_8 = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int pin = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Interpolator
		{
			
			// aapt resource value: 0x7f040000
			public const int fast_out_linear_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fast_out_slow_in = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int linear_out_slow_in = 2130968578;
			
			static Interpolator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Interpolator()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int app_name = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int pin_path_1 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int pin_path_13 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int pin_path_19 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int pin_path_25 = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int pin_path_5 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int pin_path_9 = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
